### ISSUE TITLE
JS issues

### ISSUE THREAD

**Issue by wrdana** [snag87/paint95#2]
- Clear up the console log before submitting
- You need to limit the user to an integer - consider another input type and use that for the number of pixels per row/column, because this doesn't make sense:
  ![image](https://cloud.githubusercontent.com/assets/6061907/16465931/dd7c374a-3e49-11e6-99ce-ed1e6bbbb883.png)
- Click alone doesn't work, only when I click and drag
- The code should be organized better - global variables on top, the flow of creating the elements should be triggered onload and not in the flow of the page - It's not really clear what  the flow is.
- Why are you creating a BR element? Why not just use CSS?
  `document.body.appendChild(document.createElement("br"));`
- When I hold the right key - I paint and not delete (as opposed to click...)

**Comment by HaymanLiron** [comment]
dealt with first two issues, will address others soon

**Comment by HaymanLiron** [comment]
All other issues have been addressed
